openapi: 3.0.x
info:
  title: User Service API
  version: 1.0.0
  description: 在庫情報の一括取得、アイテムIDを指定した取得を行う。
servers:
  - url: http://inventory-service:8082
    description: 開発中 microservice内で使用される。
paths:
  /inventories:
    get:
      summary: 全在庫取得
      operationId: getAllInventories
      responses:
        "200":
          description: 在庫一覧の取得に成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./schemas/inventory-schemas.yaml#/Inventory"
        "400":
          description: リクエストが不正
          content:
            application/json:
              schema:
                $ref: "./schemas/error-schemas.yaml#/Error"
        "404":
          description: リソースが存在しない
          content:
            application/json:
              schema:
                $ref: "./schemas/error-schemas.yaml#/Error"
    post:
      summary: 在庫登録
      operationId: registerInventory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/inventory-schemas.yaml#/Inventory"
      responses:
        "201":
          description: 商品の登録に成功
          content:
            application/json:
              schema:
                $ref: "./schemas/inventory-schemas.yaml#/Inventory"
        "400":
          description: リクエストが不正
          content:
            application/json:
              schema:
                $ref: "./schemas/error-schemas.yaml#/Error" 
  /inventories/{itemId}:
    get:
      summary: 任意のアイテムIDの商品取得
      operationId: getInventoryByItemId
      parameters:
        - description: アイテムID
          name: itemId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 商品の取得に成功
          content:
            application/json:
              schema:
                $ref: "./schemas/inventory-schemas.yaml#/Inventory"
        "400":
          description: リクエストが不正
          content:
            application/json:
              schema:
                $ref: "./schemas/error-schemas.yaml#/Error"
        "404":
          description: リソースが存在しない
          content:
            application/json:
              schema:
                $ref: "./schemas/error-schemas.yaml#/Error"
    #実際の操作はInventoryObjectをすべて入れ替える操作
    #実務的には全パラメータを更新することはない
    #putの学習用に定義
    put:
      summary: 任意のアイテムIDの商品数変更
      operationId: adjustInventory
      parameters:
        - description: アイテムID
          name: itemId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/inventory-schemas.yaml#/Inventory"
      responses:
        "200":
          description: 商品数変更に成功
          content:
            application/json:
              schema:
                $ref: "./schemas/inventory-schemas.yaml#/Inventory"
        "400":
          description: リクエストが不正
          content:
            application/json:
              schema:
                $ref: "./schemas/error-schemas.yaml#/Error"
        "404":
          description: リソースが存在しない
          content:
            application/json:
              schema:
                $ref: "./schemas/error-schemas.yaml#/Error"
    delete:
      summary: 任意のアイテムIDの商品削除
      operationId: deactivateInventory
      parameters:
        - description: アイテムID
          name: itemId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: 商品の削除に成功
        "400":
          description: リクエストが不正
          content:
            application/json:
              schema:
                $ref: "./schemas/error-schemas.yaml#/Error"
        "404":
          description: リソースが存在しない
          content:
            application/json:
              schema:
                $ref: "./schemas/error-schemas.yaml#/Error"